export const darkTheme = {
  taskColor: '#436680',
  taskFontColor: '#fff',
  taskFocusedFontColor: '#000',
  containerColor: '#2D3A4C',
  background: '#092133',
  buttonColor: '#FF4D2A',
  labelColor: '#ABA6A6',
  lineColor: '#818994',
  fontColor: '#fff',
  mainInputBg: '#fff',
  mainButtonColor: '#FF4D2A',
  removeButtonColor: '#F14C4C',
  checkButtonColor: '#20D77F',
  slideButtonColor: '#fff',
  slideButtonCircleColor: '#FF4D2A',
  emptyMessageColor: '#fff',
};

export const lightTheme = {
  taskColor: '#fff',
  taskFontColor: '#000',
  taskFocusedFontColor: '#000',
  containerColor: '#F4F4F4',
  background: '#E1E1E1',
  buttonColor: '#FF4D2A',
  labelColor: '#ABA6A6',
  lineColor: '#818994',
  fontColor: '#000',
  mainInputBg: '#EAEAEA',
  mainButtonColor: '#FF4D2A',
  removeButtonColor: '#F14C4C',
  checkButtonColor: '#20D77F',
  slideButtonColor: '#E1E1E1',
  slideButtonCircleColor: '#FF4D2A',
  emptyMessageColor: '#000',
};
